CANONICAL_TEAMS = {
    "ca osasuna": "CA Osasuna",
    "fc cadiz": "Cádiz CF",
    "cadiz cf": "Cádiz CF",
    "sd eibar": "SD Eibar",
    "real sociedad san sebastian": "Real Sociedad",
    "real sociedad": "Real Sociedad",
    "real valladolid": "Real Valladolid",
    "atletico madrid": "Atlético Madrid",
    "fc villarreal": "Villarreal CF",
    "villarreal cf": "Villarreal CF",
    "fc elche": "Elche CF",
    "elche cf": "Elche CF",
    "deportivo alaves": "Deportivo Alavés",
    "real betis sevilla": "Real Betis",
    "real betis": "Real Betis",
    "fc sevilla": "Sevilla FC",
    "sevilla fc": "Sevilla FC",
    "ud levante": "Levante UD",
    "levante ud": "Levante UD",
    "fc valencia": "Valencia CF",
    "valencia cf": "Valencia CF",
    "fc granada": "Granada CF",
    "granada cf": "Granada CF",
    "fc getafe": "Getafe CF",
    "getafe cf": "Getafe CF",
    "fc barcelona": "FC Barcelona",
    "athletic bilbao": "Athletic Club",
    "athletic club": "Athletic Club",
    "real madrid": "Real Madrid",
    "celta vigo": "Celta de Vigo",
    "sd huesca": "SD Huesca",
}

def get_canonical_name(normalized_name: str) -> str:
    return CANONICAL_TEAMS.get(normalized_name)
